name: Bump version and Tag
on:
  push:
    branches:
      - main
jobs:
  version-bump:
    if: github.actor != 'someci'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Authenticate with GitHub CLI
        run: |
          git config --global user.email "ci@some.engineering"
          git config --global user.name "Some CI"
          echo "${{ secrets.SOME_CI_PAT }}" | gh auth login --with-token
      - name: Bump version
        run: python tools/bump-version.py
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.SOME_CI_PAT }}
        run: |
          version=$(python tools/get-version.py)
          git add pyproject.toml fixcompliance/__init__.py
          git commit -m "Bump version to $version"
          git tag -a "$version" -m "$version"
          git push && git push --tags
